version: '2'
services:
    jhipsterandionic-app:
        image: jhipsterandionic
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsterandionic-postgresql:5432/JHipsterAndIonic
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterandionic-postgresql:
        extends:
            file: postgresql.yml
            service: jhipsterandionic-postgresql
