version: '2'
services:
    jhipsterandionic-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/JHipsterAndIonic/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=JHipsterAndIonic
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
